matrix:
  include:
    - stage: "SonarCloud"
      language: node_js
      os: linux
      node_js: "8"
      addons:
        sonarcloud:
          organization: btaluy-github
          token:
            secure: 4676bf7ed8a13fc47e442ddcc8323ec114af05a2
        script:
          - sonar-scanner -X
    - stage: "Build and Test"
      env: 
        - BuildAndroid="25"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - npm i && tns build android
      os: linux
      language: android
      dist: precise
      sudo: required
      jdk: oraclejdk8
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8
      script: npm run test-android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
  - npm install -g typings
  - wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
  - npm install -g nativescript.tgz --ignore-scripts
  - tns usage-reporting disable
  - tns error-reporting disable