stage: "Build and Test"
language: android
env:
  - BuildAndroid="26"
jdk: oraclejdk8
before_script:
  - npm install -g nativescript
  - npm install
  - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
script: npm run test
dist: precise

android:
components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-23
  - android-26
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-26