matrix:
include:
  - stage: "Lint"
    language: node_js
    node_js: "8"
    script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
  - stage: "Build and Test"
    env: 
      - BuildAndroid="26"
    language: android
    jdk: oraclejdk8
    script:
      - cd src && npm i && npm run tsc && cd ../demo
      - travis_wait travis_retry tns build android
  - language: android
    env:
      - TestVersion="latest"
    jdk: oraclejdk8
    before_script:
      - cd seed-tests && npm i
      - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
      - emulator -avd test -no-audio -no-window &
      - android-wait-for-emulator
    script: travis_wait travis_retry npm run test
    dist: precise

android:
components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-23
  - android-26
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-21

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable