branches:
  only: 
    - Master
    - Develop
matrix:
  include:
    - stage: "Install android"
    - os: linux
      language: android
      env:
        - TestVersion="latest"
      jdk: oraclejdk8
      install:
        - echo no | android create avd --force -n test -t android-26 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      dist: precise
    - stage: "install & test"
      language: node_js
      os: linux
      node_js:
        - lts/*
        - node
      install:
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - npm install

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-23
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable