stage: "Build and Test"
node_js:
   - lts/*
   - node
language: node_js
env:
  - BuildAndroid="26"
jdk: oraclejdk8
language: android
before_script:
  - echo no | android create avd --force -n test -t android-26 -b armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
script: npm run test
install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
  - npm install --loglevel verbose
dist: precise

android:
components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-23
  - android-26
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-26