branches:
  only: 
    - master
    - Develop

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - sys-img-x86-android-23
    - extra-android-m2repository

stage: "install & test"
language:
  - android
  - node_js
matrix:
  include:
    env:
      - TestVersion="latest"
      - Android="23"
    jdk: oraclejdk8
    node_js: lts/*
    before_script:
      - apt-get install qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker
      - echo no | android create avd --force -n test -t android-23 --abi default/x86
      - emulator -avd test -no-audio -no-window &
      - android-wait-for-emulator
    script:
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    after_script:
      - echo no | npm install -g nativescript
      - tns usage-reporting disable
      - tns error-reporting disable
      - npm install
      - npm run test
    dist: precise
  install: true