env:
  global:
    - NODE_VERSION=6
    - NODE_VERSION=8
    - EMULATOR_API_LEVEL=22
    - ANDROID_VERSION=25
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a
    - APPIUM_VERSION=1.7.0
    - EMULATOR_NAME=test
    - ANDROID_TAG=google_apis

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      before_install: 
        - nvm install $NODE_VERSION
      script: 
        - npm install
      addons:
        sonarcloud:
          organization: btaluy-github
          token:
            secure: feaeca75f7163a30a4724725192efb925919c9c8
      script:
        - sonar-scanner

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-25
    - android-$EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
  licenses:
    - ".+"

install:
  - nvm install $NODE_VERSION
  - npm install -g typings
  - wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
  - npm install -g nativescript.tgz --ignore-scripts
  - tns usage-reporting disable
  - tns error-reporting disable

cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle