branches:
  only: 
    - master
    - Develop

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository

stage: "install & test"
language:
  - android
  - node_js
matrix:
  include:
    env:
      - TestVersion="latest"
      - Android="26"
    jdk: oraclejdk8
    node_js: lts/*
    before_script:
      - yes | sdkmanager "platforms;android-27"
      - android-wait-for-emulator
    script:
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    after_script:
      - echo no | npm install -g nativescript
      - tns usage-reporting disable
      - tns error-reporting disable
      - npm install
      - npm run test
    dist: precise
  install: true