branches:
  only: 
    - master
    - Develop

stage: "install & test"
language:
  - android
  - node_js
matrix:
  include:
    env:
      - TestVersion="latest"
    jdk: oraclejdk8
    before_script:
      - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
      - emulator -avd test -no-audio -no-window &
      - android-wait-for-emulator
    node_js: lts/*
    script:
      - echo no | npm install -g nativescript
      - tns usage-reporting disable
      - tns error-reporting disable
      - npm install
    dist: precise
  android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-23
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  install:
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    - npm install